#pragma once

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <algorithm>
#include <utility>
#include <map>
#include <sstream>
#include <stack>
#include <unordered_set>
#include <unordered_map>
#include <numeric>
#include <array>
#include <functional>
#include <queue>

void Day1();
void Day2();
void Day3();
void Day4();
void Day5();
void Day6();
void Day7();
void Day8();
void Day9();
void Day10();
void Day11();
void Day12();
void Day13();
void Day14();